name: "[C]ontinuous [I]ntegration"
on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  test:
    uses: percebus/github-actions-npm/.github/workflows/npm_run_script.yml@main
    with:
      script: test:ci
